use_frameworks!

target 'CoordinatorExample' do
	platform :ios, '9.0'

	# Well, obviously
	pod 'Coordinator', :path => '../'

	# Auto Layout helpers in code
	pod 'TinyConstraints'

	# Image Cache
	pod 'Kingfisher'

	# JSON parser
	pod 'Marshal'

	# Nice NSTimer wrapper
	pod 'SwiftyTimer'

end

