use_frameworks!

target 'CoordinatorExample' do
	platform :ios, '9.0'

	# Well, obviously
	pod 'Coordinator', :path => '../'

	# Auto Layout helpers in code
	pod 'TinyConstraints', 	:git => 'https://github.com/radianttap/TinyConstraints.git'

	# Image Cache
	pod 'Kingfisher', 		:git => 'https://github.com/radianttap/Kingfisher.git'

	# JSON parser
	pod 'Marshal', 			:git => 'https://github.com/radianttap/Marshal.git'

	# Nice NSTimer wrapper
	pod 'SwiftyTimer', 		:git => 'https://github.com/radianttap/SwiftyTimer.git'

end

