use_frameworks!

target 'Coordinator-CP' do
	platform :ios, '10.0'

	# Well, obviously
	pod 'Coordinator', :path => '../'

	# Auto Layout helpers in code
	pod 'TinyConstraints',	:git => 'https://github.com/radianttap/TinyConstraints'

	# Image Cache
	pod 'Kingfisher', 	:git => 'https://github.com/radianttap/Kingfisher.git'

	# JSON parser
	pod 'Marshal', 	:git => 'https://github.com/radianttap/Marshal.git'

	# Nice Timer wrapper
	pod 'SwiftyTimer', 	:git => 'https://github.com/radianttap/SwiftyTimer.git'

end

